### PR TITLE
Adding xangle-beta* distributions, version 1

### PR DESCRIPTION
**Pull request by jan-kaspar**
Following the discussion in [Proton POG meeting on 22 Sep](https://indico.cern.ch/event/957567/contributions/4025681/attachments/2106851/3543363/kaspar_xangle_apertures.pdf), the 2D histograms of beta* vs. xangle have been extracted from Run2 data. For details see [this presentation](https://github.com/cms-data/CalibPPS-ESProducers/files/5311648/kaspar_xangle_beta_dist.pdf).

We would like that this update is applied both to master (11_2) and 10_6 branches.

The PR for CMSSW which consumes the newly introduced data: https://github.com/cms-sw/cmssw/pull/31639.

### CODE REVIEW

**Comment by jan-kaspar** [comment]
Kind reminder...

**Comment by yuanchao** [comment]
+1

**Comment by mrodozov** [comment]
+externals

**Comment by mrodozov** [comment]
one new file

**Pull request merged**
