### PR TITLE
Optical functions as used for UL re-reco 2016-2018

### PR DESCRIPTION
**Pull request by jan-kaspar**
This PR synchronises the repository with the UL re-reco 2016-2018 conditions.

### CODE REVIEW

**Comment by tlampen** [comment]
The current UL campaign is about pp runs of years 2016-2018 (UL 2016-2018). Therefore the concept "UL re-reco 2019" is confusing, what exactly do you mean with it?

**Comment by jan-kaspar** [comment]
> The current UL campaign is about pp runs of years 2016-2018 (UL 2016-2018). Therefore the concept "UL re-reco 2019" is confusing, what exactly do you mean with it?

I meant the re-reco started in 2019, but @tlampen is right, it was confusing. Replaced with 2016-2018 in the title and description.

**Comment by christopheralanwest** [comment]
Should this PR be tested with a cmssw PR, such as https://github.com/cms-sw/cmssw/pull/28492, or are the files not used in any standard workflow?

**Comment by jan-kaspar** [comment]
@christopheralanwest Currently, these files are not used in any standard workflow. They are useful for the "direct" simulation (see this [TWiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/TaggedProtonsDirectSimulation)) which was recently updated in https://github.com/cms-sw/cmssw/pull/28492.

**Comment by tlampen** [comment]
If we run a test together with cms-sw/cmssw#28492 , are these files used and tested?

**Comment by jan-kaspar** [comment]
@tlampen none of standard (matrix) tests would use these files. Dedicated tests based on configs from Validation/CTPPS/python/simu_config in https://github.com/cms-sw/cmssw/pull/28492 would do. I maintain such tests in a separate repo: https://github.com/jan-kaspar/proton_simulation_validation .

**Comment by jan-kaspar** [comment]
May I somehow help with this PR?

**Comment by fabiocos** [comment]
@christopheralanwest @tlampen I understand that these files are used in tests in #28492 . So this PR should not affect standard production workflows (for the time being) but may be used there. In that PR some validation plots are listed. Unless you have specific comments or requests I would suggest to move forward with this integration request, to avoid it goes forgotten

**Comment by fabiocos** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@smuzaffar FYI

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
