### PR TITLE
Optical functions for Run2 re-miniAOD and a guess for Run3.

### PR DESCRIPTION
**Pull request by jan-kaspar**
This update targets both Run 2 and Run 3.

For Run 2
  * for tracking RPs, the same data are used as in PPSOpticalFunctions_offline_v7 tag (to be used for re-miniAOD of Run2 data)
  * in addition, data for timing RPs are provided (useful e.g. for simulation)

For Run 3
  * current forecast for Run 3 optics is provided

We'd like that this update is applied to
  * 11_1 cycle
  * 10_6 cycle

### CODE REVIEW

**Comment by mrodozov** [comment]
please test
only new files, do you have any cmssw PR for this ?

**Comment by jan-kaspar** [comment]
> please test
> only new files, do you have any cmssw PR for this ?

Oops, sorry, I forgot to update the description: the new files are used with this PR: https://github.com/cms-sw/cmssw/pull/30466#issuecomment-653116915

**Comment by jan-kaspar** [comment]
@mrodozov, @smuzaffar, @tulamor: could you please review this PR and eventually sign? It doesn't change anything for the central workflows (it is only used by PPS-private "direct" simulation).

**Comment by jan-kaspar** [comment]
@pohsun, @tlampen, @tocheng, @christopheralanwest: could you please review this PR and eventually sign? It doesn't change anything for the central workflows (it is only used by PPS-private "direct" simulation).

**Comment by mrodozov** [comment]
+externals
new files

**Comment by smuzaffar** [comment]
@jan-kaspar ,  cms-sw/cmssw#30466 has been merged without this data PR but IBs are all green, so are we not using these files?

**Comment by jan-kaspar** [comment]
Both this PR and cms-sw/cmssw#30466 update the so called "direct" simulation of PPS (for more details see https://twiki.cern.ch/twiki/bin/viewauth/CMS/TaggedProtonsDirectSimulation) which is not yet included in any central workflow. That's why you don't see anything in the standard tests. On the other hand, the direct simulation is used by PPS analyzers.

**Comment by christopheralanwest** [comment]
+1

**Comment by jan-kaspar** [comment]
Many thanks! Do I understand correctly that cms-sw/cmsdist#6079 will propagate this PR changes to CMSSW_11_2 ? Is another PR needed for applying the changes in the 10_6 cycle?

**Comment by smuzaffar** [comment]
@jan-kaspar , PRs for 11.1 and 10.6 are now available.
11.1.X : https://github.com/cms-sw/cmsdist/pull/6080
10.6.X : https://github.com/cms-sw/cmsdist/pull/6081

**Comment by jan-kaspar** [comment]
> @jan-kaspar , PRs for 11.1 and 10.6 are now available.
> 11.1.X : [cms-sw/cmsdist#6080](https://github.com/cms-sw/cmsdist/pull/6080)
> 10.6.X : [cms-sw/cmsdist#6081](https://github.com/cms-sw/cmsdist/pull/6081)

Excellent, many thanks!

@fabferro: This is what we discussed during the PPS SW meeting a while ago - the PRs are already there, thanks to @smuzaffar !

**Pull request merged**
