### PR TITLE
optics for Run3 (prelim.)

### PR DESCRIPTION
**Pull request by michael-pitt**
A preliminary version of optical function using Run3 settings, produced from MAD-X source files available in `/afs/cern.ch/eng/lhc/optics/runIII/RunIII_dev/2021_V5/PROTON/`

### CODE REVIEW

**Comment by jan-kaspar** [comment]
The new data will be consumed in CMSSW with https://github.com/cms-sw/cmssw/pull/35177.

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
please test
these are new files so basically nothing to test here. The actual tests are running via https://github.com/cms-sw/cmssw/pull/35177

**Comment by tvami** [comment]
+alca
 * these are the input files needed for  cms-sw/cmssw#35177

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
